AWSTemplateFormatVersion: '2010-09-09'
Description:              container on ecs cluster

Resources:
  
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family:      apis
      Cpu:         256
      Memory:      512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name:   sentiment-analyser-api-container
          Image:  568495135738.dkr.ecr.ap-southeast-2.amazonaws.com/sentiment-analysis-repository:latest
          Cpu:    256
          Memory: 512
          PortMappings:
            - ContainerPort: 99
              Protocol:      tcp
          # logging
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         'apis'
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: 'sentiment-analyser-api'

  # defines how the task or the container will be scheduled and deployed in the cluster
  # also defines how the container instances will be registered with the load balancer listener target
  Service:  
    Type:      AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName:    sentiment-analysis-service
      TaskDefinition: !Ref Task
      Cluster:        !ImportValue 'ECSCluster'
      LaunchType:     FARGATE
      DesiredCount:   1  # number of instances of the container or task or active deployment
      DeploymentConfiguration:
        MaximumPercent:        200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue Subnet1
            - !ImportValue Subnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName:  sentiment-analyser-api-container
          ContainerPort:  99
          TargetGroupArn: !Ref TargetGroup

  # create a new target group for the application container instance (service)
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name:     sentiment-analyser-tg
      VpcId:    !ImportValue VPC
      Port:     99
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 30
      HealthCheckPath:            /healthcheck
      HealthCheckProtocol:        HTTP
      HealthCheckTimeoutSeconds:  5
      HealthyThresholdCount:      10
      TargetType:                 ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority:    2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


Outputs:

  ApiEndpoint:
    Description: Sentiment-Analyser API Endpoint
    Value:       !Join ['', ['http://', !ImportValue DomainName, '/']]
    Export:
      Name: 'SentimentAnalyserApiEndpoint'
